workflows:
  ios-workflow:
    name: ios-build
    max_build_duration: 120
    environment:
      flutter: 3.22.2
      xcode: 16.0
      ios_signing:
        distribution_type: adhoc # Use 'app_store' for TestFlight with paid account
        bundle_identifier: com.xrc_esp32_relay.espRelayControl
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - lrfpv2020@gmail.com
        notify:
          success: true
          failure: true
